#docker-composeのバージョン
#https://matsuand.github.io/docs.docker.jp.onthefly/compose/compose-file/
version: '3.8'
services:
  gitlab:
    #インストール時点の最新版にすることを推奨
    image: "gitlab/gitlab-ce:${GITLAB_TAG_VERSION:-14.0.0-ce.0}"
    container_name: gitlab
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        #公式ドキュメントを参照してください
        # https://docs.gitlab.com/omnibus/docker/README.html
        # https://docs.gitlab.com/omnibus/docker/README.html#install-gitlab-using-docker-compose
        # https://docs.gitlab.com/omnibus/docker/README.html#pre-configure-docker-container
        # = をつけてはいけない。正しいhostが参照できない場合がある
        external_url 'http://${GITLAB_HOST?err}:18080'
        gitlab_rails['gitlab_host'] = 'http://${GITLAB_HOST?err}:18080'
        gitlab_rails['gitlab_shell_ssh_port'] = 10022
        #タイムゾーン設定
        gitlab_rails['time_zone'] = 'Asia/Tokyo'
        nginx['listen_addresses'] = ['0.0.0.0', '[::]']
        #nginx['listen_port'] = 18080
        #ChromeでsecureでないcookieがブロックされることによるInvalidAuthenticityToken(status code 422)対策。
        #https://gitlab.com/gitlab-org/gitlab-foss/-/issues/50393
        nginx['proxy_set_headers'] = {
          "X-Forwarded-Proto" => "http"
        }
        nginx['redirect_http_to_https'] = false
        nginx['redirect_http_to_https_port'] = 18080
        nginx['real_ip_trusted_addresses'] = ['${GITLAB_HOST?err}','127.0.0.1']
        # 以降、カスタマイズ
        # https://github.com/gitlabhq/omnibus-gitlab/blob/master/files/gitlab-config-template/gitlab.rb.template
        # [OPTION]Maven(Gradle)パッケージレジストリの有効化
        gitlab_rails['packages_enabled'] = true
        gitlab_rails['packages_storage_path'] = "/var/opt/gitlab/gitlab-rails/shared/packages"
        # [OPTION]grafana監視を使用
        grafana['disable_login_form'] = false
        grafana['allow_user_sign_up'] = true
        grafana['admin_password'] = 'grafana'
        grafana['metrics_enabled'] = true
        grafana['metrics_basic_auth_username'] = 'grafana_metrics'
        grafana['metrics_basic_auth_password'] = 'grafana'
        prometheus['scrape_configs'] = [
          {
          'job_name': 'example',
          'static_configs' => [ 'targets' => ['${GITLAB_HOST?err}:9252'], ],
          },
        ]
        #https://gitlab.com/gitlab-org/gitlab-foss/-/issues/35300
        prometheus['monitor_kubernetes'] = false
        pages_external_url 'http://${GITLAB_HOST?err}:18080'
        gitlab_pages['enable'] = true
        gitlab_pages['dir'] = "/var/opt/gitlab/gitlab-pages"
        gitlab_pages['log_directory'] = "/var/log/gitlab/gitlab-pages"
        gitlab_pages['access_control'] = true
        gitlab_pages['inplace_chroot'] = true
    ports:
      - '18080:18080'
      - '443:443'
      - '10022:22'
    volumes:
      - type: volume
        source: gitlab-config
        target: /etc/gitlab
        volume:
          nocopy: true
      - type: volume
        source: gitlab-log
        target: /var/log/gitlab
        volume:
          nocopy: true
      - type: volume
        source: gitlab-data
        target: /var/opt/gitlab
        volume:
          nocopy: true
  runner:
    build:
      context: .
      dockerfile: gitlab-runner.Dockerfile
      args:
        IMAGE_VERSION: ubuntu-v${RUNNER_TAG_VERSION:-14.0.0}
        PROXY_URL: ${PROXY_URL}
    image: koyama/jdk-runner:ubuntu-v${RUNNER_TAG_VERSION:-14.0.0}
    container_name: gitlab-runner
    restart: always
    ports:
      #9252=Prometheus
      - '9252:9252'
    volumes:
      - gitlab-runner-config:/etc/gitlab-runner
      - gitlab-runner-home:/home/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
  database:
    build:
      context: .
      dockerfile: oracle.Dockerfile
    container_name: oracle11
    shm_size: 2g # 共有メモリは1GB以上にしないとコンテナ起動時にエラー発生
    environment:
      - TZ=Asia/Tokyo
      - LANGUAGE=ja_JP.ja
      - LANG=ja_JP.UTF-8
      - NLS_LANG=Japanese_Japan.AL32UTF8 # sqlplusの日本語化用
      - ORACLE_PWD=oracle # sys,systemのパスワード
      - ORACLE_SID=XE
      - ORACLE_PDB=pdb1
    ports:
      - 1521:1521
    volumes:
      - /oradata:/opt/oracle/oradata # データの永続化
volumes:
  gitlab-config:
  gitlab-log:
  gitlab-data:
  gitlab-runner-config:
  gitlab-runner-home: